# Site
title: Abdur Rehman
description: Full Stack Data Analyst
url: adastra21.github.io
logo: boringdata.org.png
locale: en_US

# Left Block Images
background:
  homepage: images/falling-star.png                   
  post-list: images/lighthouse-shower.png   
  default-post: images/unsplash-gallery-image-3.jpg

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Social Links
<<<<<<< HEAD
email:             hello@boringdata.org
=======
email:             hello@boringdata.org
>>>>>>> 8f286de (update bio, add new email and twitter)
linkedin:          abdurrehman21
github:            adastra21

# Plugins/Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages, CNAME]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, LICENSE, Rakefile, .sass-cache, .DS_Store]
